version: "3.3"
services:
  nginx:
    image: nginx
    container_name: nginx2
    restart: always
    ports:
      - 80:80
    volumes:
      - C:/Resources/docker/jenkins/jenkins_home/workspace/helloworld-docker-blue-green/:/etc/nginx/nginx.conf
